# Generated by Django 5.2.10 on 2026-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='flowrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
